apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-hello
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-hello
  template:
    metadata:
      labels:
        app: pod-hello
    spec:
      containers:
      - name: my-container
        image: nico385412/configmaps
        ports:
        - containerPort: 3000
        env:
        - name: NAME
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: NAME
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: COLOR